### ISSUE TITLE
Thêm phần thông tin Contest

### ISSUE THREAD

**Issue by hoangduong98998** [natsukagami/themis-web-interface#22]
Phần thông tin contest ngoài thời gian làm bài còn lại thì nên thêm một số thông tin khác.
<img src="http://i.imgur.com/LzL91f6.png" />
Thông tin nên có bao gồm
- Tên contest
- Thời gian làm bài
- Thời gian bắt đầu
- Thời gian kết thúc
- Thời gian còn lại
<img src="http://i.imgur.com/UU428wR.png" />

**Comment by buihoatpt2k3** [comment]
C:\Users\buihoatpt2k3\Downloads\themis-web-interface-0.4.0-beta2\themis-web-interface-0.4.0-beta2>set NODE_ENV=production

C:\Users\buihoatpt2k3\Downloads\themis-web-interface-0.4.0-beta2\themis-web-interface-0.4.0-beta2>set DEBUG=themis:*

C:\Users\buihoatpt2k3\Downloads\themis-web-interface-0.4.0-beta2\themis-web-interface-0.4.0-beta2>bin\node dist\index.js
module.js:472
    throw err;
    ^

Error: Cannot find module 'C:\Users\buihoatpt2k3\Downloads\themis-web-interface-0.4.0-beta2\themis-web-interface-0.4.0-beta2\dist\index.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:418:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:533:3

C:\Users\buihoatpt2k3\Downloads\themis-web-interface-0.4.0-beta2\themis-web-interface-0.4.0-beta2>pause
Press any key to continue . . .


Cho em hỏi lỗi này là bị sao ạ. Em bị lỗi này khi chạy file run.bat
