### ISSUE TITLE
Chương trình bị crash khi file trình chấm ngoài output nhiều dòng

### ISSUE THREAD

**Issue by ndkimhao** [natsukagami/themis-web-interface#9]
Khi dùng trình chấm ngoài, nếu output có nhiều dòng thì chương trình sẽ bị crash.

VD: File log 
```
asdf0001‣LINES: 100.00
LINES.pas
Dịch thành công

asdf0001‣LINES‣Test0001: 1.00
Thời gian ≈ 0.035345205 giây
Output: 6.  
Answer: 6.  
asdf0001‣LINES‣Test0002: 1.00
Thời gian ≈ 0.033979277 giây
Output: 5.  
Answer: 5.  
asdf0001‣LINES‣Test0003: 1.00
Thời gian ≈ 0.035869937 giây
Output: 2.  
Answer: 2.  
...............................................
asdf0001‣LINES‣Test0100: 1.00
Thời gian ≈ 0.045120528 giây
Output: 185.  
Answer: 185.  
```

Sinh lỗi:
```  themis:judgelog New log for asdf0001 on LINES.pas +5m
D:\Projects\themis-web-interface\controls\judgelog.js:45
                                id: res[i].match(new RegExp(rEs(`${user}‣${problem}‣`) + '(.+)' + rEs(': ') + '(.+)', 'i'))[1],
                                                                                                                           ^

TypeError: Cannot read property '1' of null
    at Function.__parse (D:\Projects\themis-web-interface\controls\judgelog.js:45:96)
    at new Log (D:\Projects\themis-web-interface\controls\judgelog.js:60:22)
    at fs.readFile (D:\Projects\themis-web-interface\controls\judgelog.js:76:33)
    at tryToString (fs.js:455:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)
error Command failed with exit code 1.
```

![image](https://cloud.githubusercontent.com/assets/7188260/21762517/ae0de55a-d68b-11e6-849d-1e0532711da8.png)

**Comment by natsukagami** [comment]
Cái này mình có thể chữa code parser để nối verdict, nhưng mà không biết check regex có đủ không.

**Comment by ndkimhao** [comment]
Em nghĩ mình có thể dùng regex để tìm những dòng có dạng
```asdf0001‣LINES‣Test0001: 1.00```
những dòng nằm giữa các dòng đó sẽ là output của trình chấm

**Comment by natsukagami** [comment]
Đang sửa trong #10

**Comment by natsukagami** [comment]
Đã sửa ở #10
